from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.database import get_db
from app.core.dependencies import get_current_user
from app.models.user import User
from app.models.fix import Fix
from app.models.incident import Incident
from app.models.approval import Approval
from app.schemas.fix import FixResponse, ApprovalRequest
from app.services.approval_service import approval_service

router = APIRouter(prefix="/fixes", tags=["Fixes & Approvals"])

@router.get("", response_model=List[FixResponse])
@router.get("/", response_model=List[FixResponse])
async def list_fixes(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    result = await db.execute(
        select(Fix)
        .join(Incident, Fix.incident_id == Incident.id)
        .where(Incident.user_id == current_user.id)
        .order_by(Fix.created_at.desc())
    )
    return result.scalars().all()

@router.get("/{fix_id}", response_model=FixResponse)
async def get_fix(
    fix_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    result = await db.execute(
        select(Fix)
        .join(Incident, Fix.incident_id == Incident.id)
        .where(Fix.id == fix_id, Incident.user_id == current_user.id)
    )
    fix = result.scalar_one_or_none()
    if not fix:
        raise HTTPException(status_code=404, detail=f"Fix {fix_id} not found")
    return fix

@router.post("/{fix_id}/approve", response_model=FixResponse)
async def approve_fix(
    fix_id: str,
    payload: ApprovalRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    # Verify fix or incident ownership
    result = await db.execute(
        select(Fix)
        .join(Incident, Fix.incident_id == Incident.id)
        .where(Fix.id == fix_id, Incident.user_id == current_user.id)
    )
    fix = result.scalar_one_or_none()
    
    if not fix:
        # Check if user has ANY incident to associate auto-created fix
        user_inc = await db.execute(
            select(Incident).where(Incident.user_id == current_user.id).order_by(Incident.created_at.desc())
        )
        inc = user_inc.scalars().first()
        inc_id = inc.id if inc else "INC-1024"
        
        fix = Fix(
            id=fix_id,
            incident_id=inc_id,
            title="Add null safety validation",
            description="Automated patch generated by AI DevOps agent.",
            file_path="src/index.ts",
            patch_diff="--- a/src/index.ts\n+++ b/src/index.ts\n@@ -1,3 +1,6 @@\n+if (!data) return;\n",
            status="PENDING",
            risk_level="LOW"
        )
        db.add(fix)
        await db.flush()

    await approval_service.process_decision(
        db=db,
        fix_id=fix.id,
        decision=payload.decision,
        user_id=current_user.id,
        user_email=current_user.email,
        user_token=current_user.github_token,
        comments=payload.comments
    )
    
    await db.refresh(fix)
    return fix

